name: Publish Python ğŸ distributions ğŸ“¦ to PyPI and TestPyPI and announce to teams

on: push

jobs:
  build-n-publish:
    runs-on: ubuntu-20.04
    name: Build and publish Python ğŸ distributions ğŸ“¦ to PyPI
    steps:
    - uses: SuffolkLITLab/ALActions/publish@main
      with:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        VERSION_TO_PUBLISH: ${{ env.GITHUB_REF_NAME }}
        TEAMS_BUMP_WEBHOOK: ${{ secrets.TEAMS_BUMP_WEBHOOK }}
