name: Run python only unit tests

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: [ main, master ]

jobs:
  test-assemblyline:
    runs-on: ubuntu-latest
    name: Run python only unit tests
    steps:
      - uses: SuffolkLITLab/ALActions/pythontests@main
