name: Run python only unit tests

on:
  push:
  workflow_dispatch:

jobs:
  test-assemblyline:
    runs-on: ubuntu-latest
    name: Run python only unit tests
    env:
      ISUNITTEST: true
    steps:
      - run: sudo apt-get update && sudo apt-get -y install libcurl4-openssl-dev build-essential python3-dev libldap2-dev libsasl2-dev slapd ldap-utils tox lcov valgrind libzbar0
      - name: Check
        uses: actions/checkout@v2
      - run: pip install virtualenv
      - run: virtualenv -p python3.8 venv
      - run: venv/bin/pip install -r docassemble/AssemblyLine/requirements.txt
      - run: venv/bin/pip install mypy 
      - run: venv/bin/pip install --editable .
      - run: venv/bin/python3 -m mypy .
      - run: venv/bin/python3 -m unittest discover
